Repository techexpertspro/portal-ascepa, pull requests merged in 2024-06, with the labels that each got.

#33 docs: Create CONTRIBUTING.md #27
  CONTRIBUTING.md
Labels: documentation

#37 docs: Create LICENSE document
  LICENSE
Labels: documentation

#40 chore: update nx packages to v19.2.1
  .gitignore
  .prettierignore
  package-lock.json
  package.json
  plugins/angular/package.json
Labels: update

#52 docs: Create Security Policy.
  docs/guides/CODE_OF_CONDUCT.md
  docs/guides/CONTRIBUTING.md
  docs/guides/SECURITY.md
Labels: documentation

#49 chore: add vercel deploy prod and deploy preview
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .gitignore
  src/app/app.component.html
Labels: setup

#54 fix: move .md to docs folder
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/SECURITY.md
Labels: bug, documentation

#62 doc(readme): add important infos and remove useless commands
  README.md
  public/header-repo.png
Labels: documentation

#72 docs: add readme badges
  README.md
Labels: documentation

#63 Feat/feature criar layout module #55
  e2e/tsconfig.json
  jest.config.app.ts
  jest.config.ts
  modules/layout/.eslintrc.json
  modules/layout/README.md
  modules/layout/jest.config.ts
  modules/layout/project.json
  modules/layout/src/index.ts
  modules/layout/src/test-setup.ts
  modules/layout/tsconfig.json
  modules/layout/tsconfig.lib.json
  modules/layout/tsconfig.spec.json
  nx.json
  project.json
  tsconfig.base.json
  tsconfig.json
Labels: refactor

#71 Translate SECURITY.md file to english
  docs/CONTRIBUTING.md
  docs/LICENSE.md
  docs/SECURITY.md
Labels: documentation

#75 ci: add sonarcloud
  .github/workflows/ci.yml
  .github/workflows/sonarcloud-scan.yml
  sonar-project.properties
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/app.component.ts
Labels: setup

#77 docs: license.md moved out of docs
  LICENSE.md
Labels: bug

#78 fix: sonar coverage on all modules
  .github/workflows/ci.yml
  .github/workflows/sonarcloud-scan.yml
  .husky/pre-commit
  README.md
  sonar-project.properties
  tools/scripts/merge-coverage.js
Labels: setup

#92 chore: add new favicon for portal Ascepa
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/site.webmanifest
  src/index.html
Labels: setup

#80 chore: add jest-axe to test accessibility
  modules/layout/src/test-setup.ts
  package-lock.json
  package.json
  src/app/app.component.spec.ts
  src/test-setup.ts
Labels: setup, a11y

#93 chore: add jest-dom to test components
  package-lock.json
  package.json
  src/app/app.component.spec.ts
  src/test-setup.ts
Labels: setup

#79 chore: include commilint on project
  .husky/commit-msg
  commitlint.config.js
  package-lock.json
  package.json
Labels: setup
