Repository techexpertspro/portal-ascepa, pull requests merged in 2024-10, with the labels that each got.

#202 [STORYBOOK] Setup inicial
  .gitignore
  modules/shared-ui/.eslintrc.json
  modules/shared-ui/.storybook/main.ts
  modules/shared-ui/.storybook/preview.ts
  modules/shared-ui/.storybook/tsconfig.json
  modules/shared-ui/project.json
  modules/shared-ui/src/lib/card/card.component.stories.ts
  modules/shared-ui/src/lib/carrousel/carrousel.component.stories.ts
  modules/shared-ui/src/lib/label/label.component.stories.ts
  modules/shared-ui/src/lib/theme-toggle/theme-toggle.component.stories.ts
  modules/shared-ui/tsconfig.json
  modules/shared-ui/tsconfig.lib.json
  nx.json
  package-lock.json
  package.json
  sonar-project.properties
  tsconfig.base.json
  tsconfig.json
Labels: setup

#180 :memo: docs: adiciona info de testes no readme
  README.md
  package.json
Labels: documentation, setup

#209 Fix/sonar occurrences
  modules/home/src/lib/home/home.component.ts
  modules/home/src/lib/latest-news/latest-news.component.html
  modules/shared-ui/src/lib/theme-toggle/theme-toggle.directive.ts
Labels: refactor

#217 :bug: fix(accessibility): adjusted heading for accessibility
  modules/layout/src/lib/header/header.component.html
Labels: a11y
