Repository techexpertspro/portal-ascepa, pull requests merged in 2024-09, with the labels that each got.

#160 Feat/seo title page
  src/app/app.routes.ts
Labels: a11y

#168 perf(title): rename title of the main page
  src/app/app.routes.ts
Labels: enhancement, performance

#171 Feat/[SEO] Adicionar Meta Tags para as Pages
  modules/home/src/lib/home/home.component.spec.ts
  modules/home/src/lib/home/home.component.ts
  src/index.html
Labels: a11y, performance

#175 169 dependabot criar dependabotyml
  .github/dependabot.yml
Labels: setup, update, dependabot
